# ZMK Studio (DYA Studio) を有効にする
CONFIG_ZMK_STUDIO=y

# 右手を親機 (Central) に設定する
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# ロータリーエンコーダー（ダイヤル）を有効にする
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 省電力設定（ワイヤレス用）
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
